from datetime import datetime, timezone, timedelta
from backend.services.metric_store import get_services, get_latest_metrics_for_service
from backend.services.alert_engine import list_alerts
from backend.services.incident_manager import list_incidents
from backend.services.monitor import get_active_anomalies, get_anomaly_history


def generate_report() -> dict:
    now = datetime.now(timezone.utc)
    services = get_services()

    all_alerts = list_alerts(limit=100)
    firing = [a for a in all_alerts if a["status"] == "firing"]
    recent_24h = [a for a in all_alerts if a.get("fired_at") and
                  (now - datetime.fromisoformat(a["fired_at"])).total_seconds() < 86400]

    incidents = list_incidents(limit=20)
    active_incidents = [i for i in incidents if i["status"] in ("investigating", "identified", "monitoring")]

    anomalies = get_active_anomalies()
    history = get_anomaly_history()

    svc_with_anomalies = set()
    for h in history:
        svc_with_anomalies.add(h.get("service", ""))
    for a in anomalies:
        svc_with_anomalies.add(a.service)

    service_statuses = []
    for svc in services:
        m = get_latest_metrics_for_service(svc)
        cpu = m.get("cpu_usage", 0)
        mem = m.get("memory_usage", 0)
        err = m.get("error_rate", 0)
        status = "critical" if (cpu > 95 or mem > 90 or err > 20) else "warning" if (cpu > 80 or mem > 75 or err > 5) else "healthy"
        service_statuses.append({"name": svc, "status": status, "cpu": cpu, "mem": mem, "err": err})

    degraded = [s for s in service_statuses if s["status"] != "healthy"]

    md = f"""# SentinelAI Infrastructure Report
**Generated**: {now.strftime('%Y-%m-%d %H:%M UTC')}

## System Overview
- **Services monitored**: {len(services)}
- **System status**: {'All Systems Operational' if not degraded else f'{len(degraded)} service(s) degraded'}
- **Active alerts**: {len(firing)}
- **Active incidents**: {len(active_incidents)}
- **Active anomalies**: {len(anomalies)}

## Active Incidents
"""
    if active_incidents:
        for inc in active_incidents:
            md += f"- **[{inc['severity']}] {inc['title']}** — Status: {inc['status']}, Services: {', '.join(inc.get('affected_services', []))}\n"
    else:
        md += "No active incidents.\n"

    md += f"\n## Alerts (Last 24 Hours)\n"
    md += f"- **Total fired**: {len(recent_24h)}\n"
    md += f"- **Currently firing**: {len(firing)}\n"
    if firing:
        md += "\n### Firing Alerts\n"
        for a in firing:
            md += f"- [{a['severity']}] **{a['title']}** — {a.get('description', '')[:80]}\n"

    md += f"\n## Service Health\n"
    md += "| Service | Status | CPU | Memory | Error Rate |\n"
    md += "|---------|--------|-----|--------|------------|\n"
    for s in service_statuses:
        status_emoji = "OK" if s["status"] == "healthy" else "WARN" if s["status"] == "warning" else "CRIT"
        md += f"| {s['name']} | {status_emoji} | {s['cpu']:.1f}% | {s['mem']:.1f}% | {s['err']:.1f}/s |\n"

    md += f"\n## Services with Recent Anomalies\n"
    if svc_with_anomalies:
        for svc in sorted(svc_with_anomalies):
            if svc:
                md += f"- {svc}\n"
    else:
        md += "No anomalies detected in the reporting period.\n"

    md += f"\n## Recommended Actions\n"
    recommendations = []
    for s in service_statuses:
        if s["status"] == "critical":
            recommendations.append(f"- **Investigate {s['name']}** immediately — critical status (CPU: {s['cpu']:.1f}%, Mem: {s['mem']:.1f}%, Errors: {s['err']:.1f}/s)")
        elif s["status"] == "warning":
            recommendations.append(f"- **Monitor {s['name']}** — warning threshold breached")

    if active_incidents:
        recommendations.append("- Review and triage all active incidents")
    if len(firing) > 5:
        recommendations.append("- Alert fatigue risk: consider tuning alert thresholds")
    if not recommendations:
        recommendations.append("- No immediate actions required. Continue monitoring.")

    md += "\n".join(recommendations)
    md += "\n\n---\n*Report generated by SentinelAI*\n"

    return {
        "markdown": md,
        "summary": {
            "services": len(services),
            "degraded": len(degraded),
            "firing_alerts": len(firing),
            "alerts_24h": len(recent_24h),
            "active_incidents": len(active_incidents),
            "active_anomalies": len(anomalies),
        },
    }
